### ISSUE TITLE
问题一堆就发出来

### ISSUE THREAD

**Issue by linjiahongx** [auto-Dog/delete_when_unzip#3]
问题1：gbk编码问题：怀疑是压缩包内文件名含有中文就不能解压
问题2：和其它issues提到的“b'7z\xbc\xaf'”一样
问题3：解压过程磁盘读取高到离谱，动不动就进度条卡死或重来
下了好久的100g文件直接损坏了
哥们你发之前都不测试的吗？

**Comment by auto-Dog** [comment]
测试做过了，在win10平台下有中文名和路径都运行成功过，源码不行可以试试发行版https://zhuanlan.zhihu.com/p/656803928。
你说的问题2，只在解压7z文件时候出现过。只有7z文件头是[b'7z\\xbc\\xaf\\x27\\x1c'](https://py7zr.readthedocs.io/en/latest/archive_format.html)，你的zip文件可能是7z伪装成的
磁盘读取高是因为单个文件移动chunk和解压删除写入同时操作
单个压缩文件解压失败，解压完成的部分就已经删了。空间和安全性不能兼得，解压确实有一定的风险，见谅
