### ISSUE TITLE
缺少对part0x.rar格式的识别

### ISSUE THREAD

**Issue by boqianlv** [auto-Dog/delete_when_unzip#4]
经过测试，part01.rar后缀名的解压，只能删除第一个文件分卷，文件夹名也会带part01，如果将文件名都改为part1，part2才会正常删除分卷，但这样的话，会导致原来的压缩软件打不开，不清楚会不会导致其他问题。

**Comment by auto-Dog** [comment]
已经解决，在创建文件夹和筛选时修改了`file_basename`的判定方式，支持识别part0x.rar
